<?php

require_once(drupal_get_path('theme', 'kelvin') . "/phpQuery-onefile.php");
require_once(drupal_get_path('theme', 'kelvin') . "/kelvin_helper.php");

function custom_menu() {
  $items['home'] = array(
    'page callback' => 'custom_home_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function custom_home_callback() {
  return "";
}

function custom_block_info() {
  $blocks['test'] = array(
    'info' => t('Testing block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function custom_block_view($delta = '') {
  $block = array ();
  $block["content"] = " ";
  switch ($delta) {
  case "test":
    $block["type"] = "test";
    $block["title"] = t("Testing block");
    $block["arr"] = array();
    break;
  }
  return $block;
}
